#!/usr/bin/env bash

# Function to perform DNS lookup and output information
runDig() {
	subarg=$1
		urlarg=$2

		record_type=$(dig "$subarg.$urlarg" | awk '/ANSWER SECTION/{getline; print $4}')
		destination=$(dig "$subarg.$urlarg" | awk '/ANSWER SECTION/{getline; print $5}')
		echo "The subdomain $subarg is a $record_type record and points to $destination"
}

# List of subdomains to check
allSubs=("www" "lb-01" "web-01" "web-02")

# Check arguments and perform DNS lookup accordingly
if [ $# -eq 1 ]; then
url="$1"
for sub in "${allSubs[@]}"; do
runDig "$sub" "$url"
done
elif [ $# -eq 2 ]; then
url="$1"
sub="$2"
runDig "$sub" "$url"
fi
