#!/usr/bin/env bash
# After configuring domain zone, use this script to output where each subdomain points to
runDig () {
	SUB=$1
		URL=$2

		dig "$SUB.$URL" | awk -v s="$SUB" '/ANSWER SECTION:/ {getline; print "The subdomain " s " is a " $4 " record and points to " $5}'
}

ALLSUBS=( "www" "lb-01" "web-01" "web-02" )

if [ $# -eq 1 ]; then
URL="$1"
for SUB in "${ALLSUBS[@]}"
do
runDig "$SUB" "$URL"
done
elif [ $# -eq 2 ]; then
URL="$1"
SUB="$2"
runDig "$SUB" "$URL"
fi 

