#!/usr/bin/env bash
#  domains and subdomains

print_domainee_() {
	local domain="$1"
		local subdomain="$2"
		dig "$subdomain.$domain" | awk '/ANSWER SECTION:/ { getline; print "The subdomain", $1, "is a", $4, "record and points to", $5 }'
}

if [ "$#" -eq 2 ]; then
print_domain_subdomain "$1" "$2"
else
domains=("www" "lb-01" "web-01" "web-02")
for subdomain in "${domains[@]}"; do
print_domain_subdomain "$1" "$subdomain"
done
fi
