#!/usr/bin/env bash
# Check if all required parameters are provided
if [ "$#" -lt 3 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
        exit 1
	fi

# Assign parameters to variables
	FILE_PATH=$2
	SSH_KEY=$1
	USER="ubuntu"
	IP_ADD=3.84.238.226

# Transfer the file using scp
	scp -o StrictHostKeyChecking=no -i "$SSH_KEY" "$FILE_PATH" $USER@$IP_ADD:~/
