#!/usr/bin/env bash
# Function to display usage message
usage() {
	echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
}

# Check if all required parameters are provided
if [ "$#" -lt 3 ]; then
    usage
    exit 1
fi

ssh_key=$4
file_path=$1
user="ubuntu"
ip_address="3.84.238.226"
scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_path" "$user"@"$ip_address":~/
