#!/usr/bin/env bash

# Function to display usage message
usage() {
	echo "Usage: $(basename "$0")"
}


if [ "$(id -u)" -ne 0 ]; then
    echo "This script must be run as root."
    exit 1
fi

apt-get update
apt-get -y install nginx

# Create HTML file with content
cat << EOF > /var/www/html/index.html
<!DOCTYPE html>
<html>
<head>
<title>Hello Helborton</title>
</head>
<body>
<h1>Hello Helborton</h1>
</body>
</html>
EOF

service nginx start

