#!/usr/bin/env bash
#  A Script that configures a new Ubuntu 


sudo apt-get update -y -qq
sudo apt-get install -y nginx


echo "Hello World!" | sudo tee /var/www/html/index.html

string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/besthor permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

sudo service nginx restart
