#!/usr/bin/env bash

# Create a custom 404 page with the required content
echo '<!DOCTYPE html><html><head><title>404 Not Found</title></head><body><h1>Ceci n'"'"'est pas une page</h1></body></html>' | sudo tee /var/www/html/404.html > /dev/null

# Create a custom Nginx configuration file for the custom 404 page
echo 'server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html;
	index index.html;

	server_name _;

	error_page 404 /404.html;
	location = /404.html {
		internal;
	}

	location / {
		try_files $uri $uri/ =404;
	}
}' | sudo tee /etc/nginx/sites-available/custom_404 > /dev/null

# Create a symbolic link to enable the custom configuration
sudo ln -s /etc/nginx/sites-available/custom_404 /etc/nginx/sites-enabled/
