#!/usr/bin/env bash
# Nginx is listening to port 80
sudo rm /etc/nginx/sites-enabled/default
sudo sed -i "s/8080/80/g" /etc/nginx/sites-available/default
sudo sed -i "s/ipv6only=on//" /etc/nginx/sites-available/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
