#!/usr/bin/env bash
#a Bash script

case $1 in
    start)
        ./manage_my_process.sh start
        ;;
    stop)
        ./manage_my_process.sh stop
        ;;
    restart)
        ./manage_my_process.sh restart
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        ;;
esac
case $1 in
    start)
        ./my_process.sh &
        echo $! > /var/run/my_process.pid
        echo "manage_my_process started"
        ;;
    stop)
        kill -TERM $(cat /var/run/my_process.pid)
        rm -f /var/run/my_process.pid
        echo "manage_my_process stopped"
        ;;
    restart)
        kill -TERM $(cat /var/run/my_process.pid)
        rm -f /var/run/my_process.pid
        ./my_process.sh &
        echo $! > /var/run/my_process.pid
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        ;;
esac
