#!/usr/bin/env bash
# script displays
# With a sleep of 2 seconds
# Prints "I am invincible!!!" on receiving a SIGTERM signal

trap 'echo "I am invincible!!!"; exit 0' SIGTERM

while true
do
  echo "To infinity and beyond"
  sleep 2
done
