#!/usr/bin/env bash
#display

for i in {1..100}; do
    output=""
    if ((i % 3 == 0)); then
        output="Fizz"
    fi
    if ((i % 5 == 0)); then
        output="${output}Buzz"
    fi

    if [ -z "$output" ]; then
        echo "$i"
    else
        echo "$output"
    fi
done

