#!/usr/bin/env bash
#The script  tell the story of /etc/passwd
while IFS=':' read -r USERNAME PASSWORD U_ID G_ID USER_INFO HOME_DIRECTORY COMMAND_SHELL
do
    echo "The user $USERNAME is part of the $G_ID gang, lives in $HOME_DIRECTORY and rides $COMMAND_SHELL. $U_ID's place is protected by the passcode $PASSWORD, more info about the user here: $USER_INFO"
done < /etc/passwd
