#!/usr/bin/env bash

sosoo=1

while [ $sosoo -le 10 ]; do
    case $sosoo in
        4)
            echo "bad luck"
            ;;
        8)
            echo "good luck"
            ;;
        *)
            echo "Best School"
            ;;
    esac

    ((sosoo++))
done
