#!/bin/bash
# Stop the existing Nginx service
pkill apache
sed -i 's/# user www-data/user nginx/g' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
